# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X2c < Formula
  desc "Convert XLSX file to CSV"
  homepage "https://github.com/gotidy/x2c"
  version "0.1.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.2/x2c_0.1.2_Darwin_arm64.tar.gz"
      sha256 "79030fa06b58f6b68fff027513dda724e4c298864009c7aea887762d66ae1117"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.2/x2c_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "ba512b628f4627681c96813c3c4822cb7f98339f26edce33933412cf9ef97908"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.2/x2c_0.1.2_Linux_arm64.tar.gz"
      sha256 "b76721f6dd1fd89ad46870465ae5125148a4f740f5b77eb8c2e660cf644bf1f0"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.2/x2c_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ecbb077ec3fe724ca2209967f3f9a76cf1c1a368a941f21b432024fab2a85837"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
  end

  test do
    system "#{bin}/x2c version"
  end
end
