# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X2c < Formula
  desc "Convert XLSX file to CSV"
  homepage "https://github.com/gotidy/x2c"
  version "0.1.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.1/x2c_0.1.1_Darwin_arm64.tar.gz"
      sha256 "ddc9b80f1e637632f854be1b7d4263ffef66ebad9b5a04b5f46dceaed3a0f183"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.1/x2c_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6b3806dd72b3190665b9193205780b311904aede083ab750d1c6ae39a0860f9d"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.1/x2c_0.1.1_Linux_arm64.tar.gz"
      sha256 "d45f4454af98715da12e5266e1c77df005999fffaf8f8c0e1f961949387b224f"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gotidy/x2c/releases/download/v0.1.1/x2c_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ab7ecd57f052dfc55bf11e7b9487d0469bb81443958dba15e54610e250019094"

      def install
        bin.install "x2c"
        # bash_completion.install "completions/x2c.bash" => "x2c"
        # zsh_completion.install "completions/x2c.zsh" => "_x2c"
        # fish_completion.install "completions/x2c.fish"
      end
    end
  end

  test do
    system "#{bin}/x2c version"
  end
end
